### ISSUE TITLE
Original author

### ISSUE THREAD

**Issue by willis7** [creising/soapui-gradle-plugin#2]
Hi @creising, I see you have decided to take a copy of the source code originally authored by myself. I'm ok with that, but in the spirit of open source, how come you didn't just fork and make a pull request for any changes you make?

**Comment by creising** [comment]
Hey @willis7. To be honest I went back and fourth trying to decide if I should fork or just clone it. I went with clone because I wanted to change some of the behavior. Since it functions differently than what you currently have, I was not sure if it is something you would even want to take. That being said, I have not issue forking it and submitting a PR if you would like to go down that route. At this point the change would be to support multiple test suites. I removed the ability to specify tests to simplify things for me. Let me know!

**Comment by willis7** [comment]
I understand :+1: . The plugin does support running multiple tests by simply defining a custom task. This is made possible through convention mapping.

Happy to keep them separate :-)
